### PR TITLE
[RTM] Always fix the domain and language when generating URLs

### LINKED ISSUE #8204: Fehlerhafte URL bei News/Event RSS-Feeds - 3.5.6
Situation:

Events/News haben eine Weiterleitung auf eine Seite/Artikel
Die Sprache wird der URL hinzugefügt

Der RSS Feed enthält bei diesen Events/News eine URL ohne Sprachenkürzel

News.php
https://github.com/contao/core/blob/master/system/modules/news/classes/News.php#L357-L370

Events.php
https://github.com/contao/core/blob/master/system/modules/calendar/classes/Events.php#L406-L419

Lösung für News.php bei interner Seite:
```
			// Link to an internal page
			case 'internal':
				if (($objTarget = $objItem->getRelated('jumpTo')) !== null)
				{
					if (\Config::get('addLanguageToUrl'))
					{
						$obj = \Pagemodel::findWithDetails($objTarget->pid);
						$strForceLang = $obj->language;
					}
					return $strBase . $this->generateFrontendUrl($objTarget->row(), NULL, $strForceLang );
				}
				break;
```

Das Problem ist in der Demo nachstellbar. Contao 3.5.6

### PR DESCRIPTION
**Pull request by leofeyer**
This PR fixed #8204 and all duplicate tickets for good (hopefully).

### CODE REVIEW

**Comment by aschempp** [comment]
Why do we need still the `$strForceLang`?

**Comment by aschempp** [comment]
Also, can we add support for `$arrRow` being a `PageModel`?

**Comment by leofeyer** [comment]
Thought about it, too. Maybe not in the bugfix release.

**Comment by aschempp** [comment]
What's the difference? If we always force domain, we always force the language…

**Comment by leofeyer** [comment]
> Why do we need still the `$strForceLang`?

We do not need it, we just keep supporting it for BC. Not sure what people have used it for …

**Comment by Toflar** [comment]
> Not sure what people have used it for …

To force the language, like the parameter says? If you don't have any front end context, how would you generate it correctly? :-)

BTW: I think I have a better approach for your code performance wise which will be fully backwards compatible:

* Check if `tl_page.language` has changed in `save_callback` and if so, update all child records with it.
* Modify the `PageModel` and introduce a `getLanguage()` method:

```php
public function getLanguage()
{
    // Ensure root page language is inherited if not set by save_callback (BC)
    if ('' === $this->language) {
        $this->loadDetails();
    }

    return $this->language;
}
```
* Support passing the `\PageModel` to `\Controller::generateFrontendUrl()` then instead of using `$arrRow['language']` use `\PageModel::getLanguage()`.

Why in 3.5: Well, we have to change the handling because it's buggy at the moment but if we already change it then we should make it right :-)

**Comment by leofeyer** [comment]
> To force the language, like the parameter says? If you don't have any front end context, how would you generate it correctly? :-)

No front end context is required. It will set the language and domain based on `$page->rootLanguage` and `$page->domain`, which are both set in `PageModel::loadDetails()`.

> I think I have a better approach for your code performance wise which will be fully backwards compatible

How is your code performing better? We'd still have to bubble up to the root page to check the domain, wouldn't we?

**Comment by leofeyer** [comment]
Not to forget `$page->trail`, which also required to load the page details.

**Comment by leofeyer** [comment]
The PR is ready to merge now. Please review one last time.

File: system/modules/core/classes/Backend.php [hunk 1]
```diff
@@ -660,20 +660,21 @@ protected function getBackendModule($module)
...
 	 * @return array
 	 */
-	public static function findSearchablePages($pid=0, $domain='', $blnIsSitemap=false, $strLanguage='')
+	public static function findSearchablePages($pid=0, $domain='', $blnIsSitemap=false)
 	{
-		$time = \Date::floorToMinute();
-		$objDatabase = \Database::getInstance();
-
-		// Get published pages
-		$objPages = $objDatabase->prepare("SELECT * FROM tl_page WHERE pid=? AND (start='' OR start<='$time') AND (stop='' OR stop>'" . ($time + 60) . "') AND published='1' ORDER BY sorting")
```
Comment (aschempp) [inline system/modules/core/classes/Backend.php]: If I remember correctly, we intentionally do not use models here because of performance and memory …

File: system/modules/core/classes/Frontend.php [hunk 2]
```diff
@@ -469,7 +469,7 @@ protected function jumpToOrReload($intId, $strParams=null, $strForceLang=null)
 			{
 				if ($intId['id'] != $objPage->id  || $blnForceRedirect)
 				{
-					$this->redirect($this->generateFrontendUrl($intId, $strParams, $strForceLang));
```
Comment (aschempp) [inline system/modules/core/classes/Frontend.php]: We must forward the language parameter if it's set, or it would potentially alter behavior.

File: system/modules/core/library/Contao/Controller.php [hunk 3]
```diff
@@ -1075,14 +1075,23 @@ public static function redirect($strLocation, $intStatus=303)
...
 		$strUrl = '';
 
+		if (func_num_args() > 2)
+		{
+			@trigger_error('Using Controller::generateFrontendUrl() with more than two arguments has been deprecated and will no longer work in Contao 5.0.', E_USER_DEPRECATED);
+		}
+
+		if (!isset($arrRow['rootId']))
+		{
+			$arrRow = \PageModel::findWithDetails($arrRow['id'])->row();
```
Comment (aschempp) [inline system/modules/core/library/Contao/Controller.php]: I think we should only fetch the domain (and maybe language) here. We don't know if the alias in the array is actually the same as the given page ID…

File: system/modules/core/models/ArticleModel.php [hunk 4]
```diff
@@ -203,6 +203,34 @@ public static function findPublishedByPidAndColumn($intPid, $strColumn, array $a
...
+	 * @param array   $arrOptions An optional options array
+	 *
+	 * @return \Model\Collection|\ArticleModel[]|\ArticleModel|null A collection of models or null if there are no articles in the given column
+	 */
+	public static function findPublishedWithTeaserByPid($intPid, array $arrOptions=array())
+	{
+		$t = static::$strTable;
+		$arrColumns = array("$t.pid=? AND $t.showTeaser=1");
+
+		if (!BE_USER_LOGGED_IN)
```
Comment (aschempp) [inline system/modules/core/models/ArticleModel.php]: Checking for the backend user is a new and undesired case here, because the searchable pages must not be related to the user being logged in.

File: system/modules/core/modules/ModuleLogin.php [hunk 5]
```diff
@@ -76,7 +76,8 @@ public function generate()
 				// Redirect to the jumpTo page
 				if ($this->jumpTo && ($objTarget = $this->objModel->getRelated('jumpTo')) !== null)
```
Comment (aschempp) [inline system/modules/core/modules/ModuleLogin.php]: A general idea. If we would write `($objTarget = $this->objModel->getRelated('jumpTo')) instanceof \PageModel`, it would be more safe, we would not need the `@var` hint and work exactly the same.

File: system/modules/core/classes/Backend.php (hunk 1 above)
Comment (leofeyer) [inline system/modules/core/classes/Backend.php]: I don't remember anything alike. Has there been a ticket?

File: system/modules/core/classes/Frontend.php (hunk 2 above)
Comment (leofeyer) [inline system/modules/core/classes/Frontend.php]: Why should we? It would only trigger the deprecation warning.

File: system/modules/core/library/Contao/Controller.php (hunk 3 above)
Comment (leofeyer) [inline system/modules/core/library/Contao/Controller.php]: Isn't this exactly what `findWithDetails()` does?

File: system/modules/core/classes/Frontend.php (hunk 2 above)
Comment (aschempp) [inline system/modules/core/classes/Frontend.php]: it would potentially alter behavior, because it could already be set. We're doing the same in `PageModel::getFrontendUrl()`

File: system/modules/core/models/ArticleModel.php (hunk 4 above)
Comment (leofeyer) [inline system/modules/core/models/ArticleModel.php]: This is the default code snippet to make the front end preview work, so I don't think it is "undesired". What is the exact error case?

File: system/modules/core/modules/ModuleLogin.php (hunk 5 above)
Comment (leofeyer) [inline system/modules/core/modules/ModuleLogin.php]: I like the idea. We should generally change this in version 4.2.

Comment (leofeyer) [inline system/modules/core/modules/ModuleLogin.php]: I have created a ticket: https://github.com/contao/core-bundle/issues/451

File: system/modules/core/classes/Frontend.php (hunk 2 above)
Comment (leofeyer) [inline system/modules/core/classes/Frontend.php]: I have changed it in 57abb98453bb2673965fc11c3f33eb7c3bd9b3c6.

File: system/modules/core/classes/Backend.php (hunk 1 above)
Comment (Toflar) [inline system/modules/core/classes/Backend.php]: I remember something like this as well. Cannot find it though but it sure is an issue with a lot of pages. Please do not change this!

File: system/modules/core/library/Contao/Controller.php (hunk 3 above)
Comment (aschempp) [inline system/modules/core/library/Contao/Controller.php]: Yes, but it will overwrite whatever was in `$arrRow` passed into the method.

File: system/modules/core/models/ArticleModel.php (hunk 4 above)
Comment (aschempp) [inline system/modules/core/models/ArticleModel.php]: It is not the same behavior as it previously was. In this implementation, invisible articles would be added to the search index if `BE_USER_LOGGED_IN` is `true` (for whatever reason).

File: system/modules/core/classes/Backend.php (hunk 1 above)
Comment (leofeyer) [inline system/modules/core/classes/Backend.php]: I have to change it to fix the initial problem.

Comment (Toflar) [inline system/modules/core/classes/Backend.php]: This will fail miserably, I tell you. This is a no go, I'm sorry.

File: system/modules/core/models/ArticleModel.php (hunk 4 above)
Comment (leofeyer) [inline system/modules/core/models/ArticleModel.php]: They would only be added if `BE_USER_LOGGED_IN` is `false`, which is never the case in the back end. Also, this is a general model method, which is **not** specifically tailored to the `findSearchablePages()` method!

File: system/modules/core/classes/Backend.php (hunk 1 above)
Comment (leofeyer) [inline system/modules/core/classes/Backend.php]: You are telling me this based on something you think you remember, which however is nowhere documented?

**Comment by leofeyer** [comment]
I have investigated a bit. Here are some findings of where not to use models:

* https://github.com/contao/core/blob/master/system/modules/core/forms/Form.php#L525-L526
* https://github.com/contao/core/blob/master/system/modules/core/classes/Theme.php#L560-L561

Rebuilding the search index is not one of them. Also, I have debugged rebuilding the search index with and without models:

**With models**

with-models

**Without models**

without-models

Using models requires 10% more memory, however, it also decreases the number of database queries and the number of rows which need to be transferred.

@Toflar What exactly are your concerns?

**Comment by Toflar** [comment]
Try this on an installation with 3000 pages that are split over 12 domains times 4 languages (= 48 root pages). I think it's going to fail :smile:

File: system/modules/core/classes/Backend.php (hunk 1 above)
Comment (aschempp) [inline system/modules/core/classes/Backend.php]: https://github.com/contao/core/issues/7928#issuecomment-130788699

File: system/modules/core/models/ArticleModel.php (hunk 4 above)
Comment (aschempp) [inline system/modules/core/models/ArticleModel.php]: > Also, this is a general model method, which is not specifically tailored to the findSearchablePages() method!

Which is the problem in my opinion. Just saying, you're changing the system behavior in a patch release, that's a very bad idea…

**Comment by leofeyer** [comment]
I found the ticket about what you think to remember: #7928

We have also discussed that we need to use the database class again, but then we found [a bug](https://github.com/contao/core-bundle/commit/faeea6e7ffa37ede2a21f62213fe01047815d00f) in the `Model` class, which turned out to cause the problems.

After fixing the bug, the memory issues were gone. So we can safely merge this PR now.

File: system/modules/core/models/ArticleModel.php (hunk 4 above)
Comment (leofeyer) [inline system/modules/core/models/ArticleModel.php]: I am not changing anything, because `BE_USER_LOGGED_IN` **will always be true** in the back end!

Comment (aschempp) [inline system/modules/core/models/ArticleModel.php]: I hope you mean the opposite? :laughing:

Comment (leofeyer) [inline system/modules/core/models/ArticleModel.php]: No?

**Comment by aschempp** [comment]
> After fixing the bug, the memory issues were gone.

That's just not true. The last comment was "please test", so we don't know if anything changes. The major difference (in my opinion) is that the models will be kept in the registry indefinitely, whereas the database result will be removed from memory when not used anymore.

File: system/modules/core/models/ArticleModel.php (hunk 4 above)
Comment (aschempp) [inline system/modules/core/models/ArticleModel.php]: Well …
1. `BE_USER_LOGGED_IN` **is always false in the backend**
2. Would it be true, the `start`/`stop` filter would not take place, which would be wrong in the `getSearchablePages` context.

**Comment by leofeyer** [comment]
Of course they were gone. We have tested the change extensively, we have just not commented in the ticket. But it was only closed two weeks after finding the bug.

File: system/modules/core/models/ArticleModel.php (hunk 4 above)
Comment (leofeyer) [inline system/modules/core/models/ArticleModel.php]: You are right. My bad.

Comment (leofeyer) [inline system/modules/core/models/ArticleModel.php]: But it does not change the fact that the PR does not change the current behavior in the back end.

Comment (leofeyer) [inline system/modules/core/models/ArticleModel.php]: If someone executes `Backend::findSearchablePages()` in the front end, it might include unpublished pages now. But you should not have done this anyway (the class is called `Backend` for a reason).

Comment (aschempp) [inline system/modules/core/models/ArticleModel.php]: That's what I mean. We just don't know. To my gut feeling, we're changing too much, we should just fix the initial problem and not start adding new behavior.

Comment (aschempp) [inline system/modules/core/models/ArticleModel.php]: Also be aware that your current comparison will result in a wrong result if the constant is not defined (e.g. for a custom entry point).

File: system/modules/core/library/Contao/Controller.php (hunk 3 above)
Comment (leofeyer) [inline system/modules/core/library/Contao/Controller.php]: I see. Changed in 7bf3c75967f0c8901c8e14e532b46a907bd50f9b.

**Comment by Toflar** [comment]
I tried to do some tests to back my use case and ended up with a regular page model requiring more or less 20kb of RAM. So for 3000 pages it would require about 60 MB RAM which is fine then I think :-) If they are split over 48 root pages it will certainly need quite a lot more memory but it should still be fine. So I guess my concerns are refuted :-) 

However, I still think, inheriting `dns`, `language` and whatever other columns are needed to generate a front end url, is the way to go. You can safely generate a front end url from one single database row without having to load the model and its root page and bubble up all the pages to load the details then. It would greatly improve performance, memory consumption and developer experience :-)

**Comment by aschempp** [comment]
> However, I still think, inheriting dns, language and whatever other columns are needed to generate a front end url, is the way to go. You can safely generate a front end url from one single database row without having to load the model and its root page and bubble up all the pages to load the details then. It would greatly improve performance, memory consumption and developer experience :-)

That's certainly something we should think about, but certainly not in the 3.5.7 patch release ^^

**Comment by leofeyer** [comment]
> However, I still think, inheriting `dns`, `language` and whatever other columns are needed to generate a front end url, is the way to go.

Yes, I'm totally with you on this one. However, that is a different issue.

The problem is that storing the fields in the database is pretty cumbersome and also error-prone, because you have to keep it in sync when the root page changes. There are some solutions for this problem already and backbone87 has implemented one in #6193 (his initial issue was #6830).

**Comment by leofeyer** [comment]
So now that we have settled this and that I have changed all you have suggested, can I merge the PR?

**Comment by Toflar** [comment]
Imho, yes.

**Comment by leofeyer** [comment]
Ah, no, I cannot. I have not solved [this issue](https://github.com/contao/core/pull/8238#discussion_r54392977) brought up by @aschempp :(

File: system/modules/core/models/ArticleModel.php (hunk 4 above)
Comment (leofeyer) [inline system/modules/core/models/ArticleModel.php]: I have reverted the changes in a83463a9015027d76706e41a920649bded8b1124.

**Comment by leofeyer** [comment]
> You could have added a flag to $arrOptions to disable the fePreview check?

I have thought about exactly this, too :smile:

I have not asked you though, because I also think it is a new feature. But we should definitely implement it!

**Comment by leofeyer** [comment]
I have created a separate ticket: contao/core-bundle#452

**Comment by leofeyer** [comment]
Merged in c68d813969e0c7c4ae6b1716a71ea6edba00bb8e.
