### PR TITLE
fix cache key usage

### LINKED ISSUE #8694: inconsistent cache key generation
There is an inconsistency with the cache key generation and usage. When a page is generated for the page cache, `FrontendTemplate::addToCache` _always_ uses the __current host__ for the cache key: 
[system/modules/core/classes/FrontendTemplate.php#L216-L220](https://github.com/contao/core/blob/3.5.25/system/modules/core/classes/FrontendTemplate.php#L216-L220)
```php
$strCacheKey = \Environment::get('host') . '/empty.' . $objPage->language;
…
$strCacheKey = \Environment::get('host') . '/' . \Environment::get('request');
```
However, `Automator::generateConfigCache` _always_ uses either the _DNS setting_ from the page object or `*`: 
[system/modules/core/library/Contao/Automator.php#L539](https://github.com/contao/core/blob/3.5.25/system/modules/core/library/Contao/Automator.php#L539)
```php
$strBase = ($objPages->dns ?: '*');
```
So when the internal cache is active, the resulting `system/cache/config/mapping.php` will look like this for example:
```php
<?php

return array (
  '*/empty.fallback' => '*/empty.de',
  '*/empty.de' => '*/empty.de',
);
```
But the cache file was generated with `example.org/empty.de` as its cache key.

This then leads to the start page _never_ being served from the page cache, if the internal cache is built and no DNS setting was present in the website root.

### PR DESCRIPTION
**Pull request by fritzmg**
This fixes #8694.

Explanation:

* The `Automator` uses `$objPages->dns ?: '*'` [here](https://github.com/contao/core/blob/3.5.25/system/modules/core/library/Contao/Automator.php#L539) for creating the mappings of the _empty request_ cache key.
* However, `FrontendTemplate::addToCache` never actually uses `*` when creating the cache key (for the empty request), see [here](https://github.com/contao/core/blob/3.5.25/system/modules/core/classes/FrontendTemplate.php#L216). Thus the cache key for the empty request will always be `example.org/empty…`.
* Thus `FrontendIndex::outputFromCache` never actually finds a cache entry for the empty request [here](https://github.com/contao/core/blob/3.5.25/system/modules/core/controllers/FrontendIndex.php#L318-L431) since it will always be looking for `*/empty…` due to the mapping (if no DNS setting was made in the root page).

_Note:_ if the internal cache is __not__ in use or created, then [this Problem](https://github.com/contao/core/issues/7618#issuecomment-292555484) still remains.

### CODE REVIEW

File: system/modules/core/classes/FrontendTemplate.php [hunk 1]
```diff
@@ -251,7 +251,7 @@ protected function addToCache()
 			$strHeader = sprintf
 			(
 				"<?php /* %s */ \$expire = %d; \$content = %s; \$type = %s; \$files = %s; \$assets = %s; ?>\n",
-				$strCacheKey,
+				ltrim($strCacheKey, '*'),
```
Comment (fritzmg) [inline system/modules/core/classes/FrontendTemplate.php]: Just to comment on why this is necessary: when the cache key starts with `*`, the resulting PHP header of the cache file would look like this:
```php
<?php /* */empty.de */ $expire = 1494230344; $content = 'text/html'; $type = 'regular'; $files = ''; $assets = ''; ?>
```
This is invalid PHP syntax of course, thus I simply remove the `*` for the header.

File: system/modules/core/classes/FrontendTemplate.php [hunk 2]
```diff
@@ -213,7 +213,7 @@ protected function addToCache()
 			// If the request string is empty, use a special cache tag which considers the page language
 			if (\Environment::get('request') == '' || \Environment::get('request') == 'index.php')
 			{
-				$strCacheKey = \Environment::get('host') . '/empty.' . $objPage->language;
+				$strCacheKey = ($objPage->domain ?: '*') . '/empty.' . $objPage->language;
```
Comment (leofeyer) [inline system/modules/core/classes/FrontendTemplate.php]: Shouldn't this be `$objPage->dns`?

File: system/modules/core/classes/FrontendTemplate.php (hunk 1 above)
Comment (leofeyer) [inline system/modules/core/classes/FrontendTemplate.php]: How about `"<?php\n\n// %s\n\$expire = %d;\n\$content = %s;\n\$type = %s;\n\$files = %s;\n\$assets = %s;\n\n?>\n"` instead?

**Review by leofeyer — CHANGES_REQUESTED** [review]

File: system/modules/core/classes/FrontendTemplate.php (hunk 2 above)
Comment (fritzmg) [inline system/modules/core/classes/FrontendTemplate.php]: No, `$objPage->dns` is only set for root pages. For other pages this information is saves in `->domain`. See [system/modules/core/models/PageModel.php#L868](https://github.com/contao/core/blob/3.5.25/system/modules/core/models/PageModel.php#L868)

**Comment by fritzmg** [comment]
> How about "<?php\n\n// %s\n\$expire = %d;\n\$content = %s;\n\$type = %s;\n\$files = %s;\n\$assets = %s;\n\n?>\n" instead?

Sure, that should work too :)

File: system/modules/core/classes/FrontendTemplate.php (hunk 1 above)
Comment (fritzmg) [inline system/modules/core/classes/FrontendTemplate.php]: Sure, that should work too :). Should even work without the line breaks, I think.

Comment (fritzmg) [inline system/modules/core/classes/FrontendTemplate.php]: I have changed it now.

**Review by leofeyer — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]
